### ISSUE TITLE
Crashes upon load if installed from VS Code

### ISSUE THREAD

**Issue by bean5** [amorenew/alps_rfid_ax6737#2]
**Expected**
Code builds and runs on ax6737 65n device.

**Actual**
* Code builds
* Code **does not** run -- crashes upon opening

**About My Device**
_Model Number_: ax6737_65_n
_Android version_: 7.0
_Kernel version_: 3.18.35
_Custom build version_: alps-mp-n0.mp1-V1.0.2_ax6737.65.n

There is no error message I can use to determine why it crashes.

**Comment by bean5** [comment]
@amorenew

**Comment by amorenew** [comment]
https://github.com/amorenew/alps_rfid_ax6737/tree/master/android/src/main/jniLibs/armeabi-v7a
jni uses 64bit
check the solution here
https://github.com/amorenew/alps_rfid_n6737/issues/5

**Comment by bean5** [comment]
See https://github.com/amorenew/alps_rfid_n6737/issues/5#issuecomment-577435354

**Comment by bean5** [comment]
Oh, README update is ready for both projects.

I have other changes I will advise in separate PRs.
