### ISSUE TITLE
Stream never sends event

### ISSUE THREAD

**Issue by bean5** [amorenew/alps_rfid_ax6737#8]

**Comment by amorenew** [comment]
@bean5 Which library works for your model ax6737 or n6737?

**Comment by bean5** [comment]
@amorenew Probably ax6737 because when I attach the Android phone to the computer, it is called `ax6737 65n`.

**Comment by amorenew** [comment]
![IMG_20200205_134728058](https://user-images.githubusercontent.com/2842459/73882795-69af0600-486b-11ea-8359-5941615b75ed.jpg)
@bean5 
ALPS is an Android device and it is customizable.
So your Chinese provider could add different components like RFID or NFC or Fingerprint
As I saw **your RFID is different than my RFID Component**.
I will close the issue as it is a different Hardware but I still can support you if you have the native SDK and you want to build a Flutter plugin

**Comment by bean5** [comment]
Thank you. I will email separately.

**Comment by bean5** [comment]
Thank you. I would like help. It is RFID that I want to make work.

**Comment by amorenew** [comment]
@bean5 Check the steps on https://github.com/amorenew/alps_rfid_n6737/issues/4
